steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "web-server"
      - "--image"
      - "gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--set-secrets=GCP_DATA_STORAGE=GCP_DATA_STORAGE:1"
      - "--set-secrets=ADMIN_USERNAME=ADMIN_USERNAME:1"
      - "--set-secrets=ADMIN_PASSWORD_HASH=ADMIN_PASSWORD_HASH:1"
      - "--set-secrets=NEXTAUTH_URL=NEXTAUTH_URL:1"
      - "--set-secrets=NEXTAUTH_SECRET=NEXTAUTH_SECRET:1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "TZ=Asia/Tokyo"
      - "--service-account"
      - "web-server@tbsten-me.iam.gserviceaccount.com"
      - "--min-instances"
      - "0"
images:
  - "gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA"
